services:
  ollama:
    image: ollama/ollama:latest
    ports: ["11435:11434"]
    volumes: [ollama_data:/root/.ollama]
    environment: 
      - OLLAMA_HOST=0.0.0.0:11435
    restart: unless-stopped
    entrypoint: ["/bin/sh", "-c"]
    command: ["sleep 10 && /bin/ollama serve"]

  onnx-runtime:
    image: mcr.microsoft.com/onnxruntime/server:latest
    container_name: edge-ai-onnx
    ports:
      - "8001:8001"
    restart: unless-stopped

  nginx-gateway:
    image: nginx:alpine
    container_name: edge-ai-gateway
    ports:
      - "30080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ollama
      - onnx-runtime
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    ports: ["9090:9090"]
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    depends_on:
      - ollama

  grafana:
    image: grafana/grafana:latest
    ports: ["3007:3000"]
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_DEFAULT_THEME=light
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  ollama_data:
  prometheus_data:
  grafana_data:
