site_name: Wrona Edge AI Platform
site_description: 'Comprehensive Edge AI platform with model serving, monitoring, and benchmarking'
site_author: 'Wrona AI Team'
repo_url: https://github.com/wronai/edge
repo_name: 'GitHub'

# Documentation theme
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.annotate
    - content.code.copy
  icon:
    repo: fontawesome/brands/github
  favicon: images/favicon.ico

# Navigation
nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quickstart: getting-started/quickstart.md
  - User Guide:
    - Model Management: guide/model-management.md
    - Model Conversion: guide/conversion.md
    - Model Benchmarking: guide/benchmarking.md
    - Monitoring: guide/monitoring.md
  - API Reference:
    - Core: api/core.md
    - CLI: api/cli.md
    - Models: api/models.md
    - Converters: api/converters.md
  - Development:
    - Setup: development/setup.md
    - Testing: development/testing.md
    - Contributing: development/contributing.md
  - Changelog: CHANGELOG.md
  - License: LICENSE.md

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true

# Plugins
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            show_root_heading: false
            show_source: true
  - mkdocs-jupyter:
      include_source: true

# Customization
extra_css:
  - css/extra.css
  - https://unpkg.com/tippy.js@6/dist/tippy.css

extra_javascript:
  - js/extra.js
  - https://unpkg.com/tippy.js@6/dist/tippy.umd.min.js
  - https://unpkg.com/mermaid@9/dist/mermaid.min.js

# Build options
strict: true
use_directory_urls: true

# Copyright
copyright: Copyright &copy; 2025 Wrona AI Team
