global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: '/metrics'
    scheme: 'http'

  # Commenting out ollama for now as it's not exposing metrics
  # - job_name: 'ollama'
  #   static_configs:
  #     - targets: ['ollama:11434']
  #   metrics_path: '/metrics'
  #   scheme: 'http'
