global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ollama'
    static_configs:
      - targets: ['ollama:11435']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'onnx-runtime'
    static_configs:
      - targets: ['onnx-runtime:8001']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'nginx-gateway'
    static_configs:
      - targets: ['nginx-gateway:80']
    metrics_path: /nginx_status
    scrape_interval: 30s
